// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ1_jQcgQ4fapiUXqBzaHu0L5LThzdBdM',
    appId: '1:48983974458:web:823c366fb88f756376cb03',
    messagingSenderId: '48983974458',
    projectId: 'guzzler-7f112',
    authDomain: 'guzzler-7f112.firebaseapp.com',
    storageBucket: 'guzzler-7f112.appspot.com',
    measurementId: 'G-Z37Z0N23T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd8L3fkyq-iT1KpHhLxngTNvTdPRFOUq4',
    appId: '1:48983974458:android:28e450b8618539a076cb03',
    messagingSenderId: '48983974458',
    projectId: 'guzzler-7f112',
    storageBucket: 'guzzler-7f112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeHFw25waaN-cF85WiBi_CuE_Tns8RARI',
    appId: '1:48983974458:ios:b8653038f24e4d6476cb03',
    messagingSenderId: '48983974458',
    projectId: 'guzzler-7f112',
    storageBucket: 'guzzler-7f112.appspot.com',
    iosBundleId: 'com.example.guzzler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeHFw25waaN-cF85WiBi_CuE_Tns8RARI',
    appId: '1:48983974458:ios:ff10c6a12343725d76cb03',
    messagingSenderId: '48983974458',
    projectId: 'guzzler-7f112',
    storageBucket: 'guzzler-7f112.appspot.com',
    iosBundleId: 'com.example.guzzler.RunnerTests',
  );
}
